"""SQLAlchemy declarative models — JobRadar persistence layer (v1).

Why this file exists
====================
The exercise on this branch is *schema + migration files only*. The FastAPI
routes (``backend/routes/*.py``) still use their in-memory ``_FOO_DB`` dicts
for the demo and they have to keep working without change — that's the
explicit user requirement.

This module therefore defines:

1. The **declarative ``Base``** that Alembic reads to autogenerate
   migration scripts. Any new column added here will be picked up by
   ``alembic revision --autogenerate`` even though the routes never query
   the database today.
2. The full set of **Postgres-native enum types** mirroring the
   ``Literal[...]`` Pydantic enums in :mod:`backend.routes.companies`,
   :mod:`backend.routes.jobs`, :mod:`backend.routes.applications`,
   :mod:`backend.routes.qa_bank`, and :mod:`backend.routes.outreach`.
   Expanding any of those enums requires updating both sides together.
3. Sixteen tables — see ``docs/02-version2-add-postgres.md`` for the full
   design rationale. Each table's columns mirror the corresponding Pydantic
   model 1-for-1, so the eventual route rewrite is mechanical (replace
   ``_FOO_DB[id]`` with ``(await session.execute(select(Foo).where(...))).scalar_one_or_none()``).

Design rules baked into every model
===================================

* **UUID primary keys** generated by Postgres (``gen_random_uuid`` from
  ``pgcrypto``; built-in since PG 13). The migration enables the
  ``pgcrypto`` extension explicitly so Supabase projects that arrive at
  PG 16 without it enabled by default still work.
* **TIMESTAMPTZ** for every timestamp. Existing routes emit ISO-8601
  strings; the new schema stores real ``datetime`` objects and the route
  rewrite can do the conversion at the Pydantic boundary.
* **TEXT[] for tag-shaped arrays** (``tags``, ``hiring_signals``,
  ``target_roles``). Postgres array literals (``ANY(tags)``,
  ``@> ARRAY['python']``) are dramatically cheaper to index with GIN
  than JSONB for the simple-string-tuple use case these enums have.
* **Supabase Storage reference (not ``bytea``) for resume bytes.** 10 MiB
  resumes bloat Postgres pages and tank the buffer cache; the schema
  stores a ``storage_path`` and the route rewrite will upload to Supabase
  Storage. The ``resumes`` table now also has a partial-unique index on
  ``is_default`` to enforce the "single default resume" invariant that
  :func:`routes.resumes.patch_resume` enforces in Python today.
* **Singleton tables** (``preferences``, ``pipeline_status``) use
  ``CHECK (id = 1)`` to enforce single-row at the database level —
  cheaper and more reliable than application-level guards.
* **No soft-delete.** JobRadar expresses lifecycle through explicit
  ``status`` enums (``dismissed``, ``rejected``, ``ghosted``); a global
  ``deleted_at`` would litter every query with a soft-delete predicate
  for zero benefit.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, ENUM, JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def _utcnow() -> datetime:
    """Naive-free ``datetime.utcnow`` shim.

    Returns timezone-aware UTC datetimes so asyncpg doesn't need to assume
    ``TIMESTAMP`` semantics — Postgres ``TIMESTAMPTZ`` always serialises
    UTC anyway, and ``datetime.utcnow()`` is deprecated in 3.12+.
    """
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# Declarative base
# ---------------------------------------------------------------------------
class Base(DeclarativeBase):
    """All models inherit from this — Alembic autogenerate reads ``Base.metadata``."""
    pass


# ---------------------------------------------------------------------------
# Shared enum registries. Keep this section in sync with the Literal[...]
# enums in backend/routes/* — expansions go on both sides together.
# ---------------------------------------------------------------------------
COMPANY_CATEGORY_VALUES = ("boards", "funding", "ngos", "oss", "remote")
COMPANY_STATUS_VALUES = (
    "saved",
    "interested",
    "dismissed",
    "outreach_sent",
    "engaged",
)
JOB_STATUS_VALUES = (
    "in_review",
    "approved",
    "rejected",
    "applied",
    "flagged",
)
APPLICATION_STATUS_VALUES = (
    "submitted",
    "interview",
    "rejected",
    "offer",
    "ghosted",
)
QA_ANSWER_TYPE_VALUES = ("short_text", "long_text")
OUTREACH_TYPE_VALUES = ("email", "twitter_dm", "linkedin")
SCANNER_KIND_VALUES = ("funding", "remote", "ngos", "oss", "boards")
ATS_BOARD_VALUES = ("ashby", "lever", "greenhouse", "remotive", "remoteok", "hackernews")
ATS_ORG_STATUS_VALUES = ("active", "missing", "benched")
PIPELINE_STATE_VALUES = ("idle", "running", "error")

# Single source of truth for Postgres enum creation — registered as
# ``postgresql.ENUM(..., name=...)`` instances so Alembic emits them
# verbatim in CREATE TYPE / DROP TYPE statements.
company_category_t = ENUM(*COMPANY_CATEGORY_VALUES, name="company_category")
company_status_t = ENUM(*COMPANY_STATUS_VALUES, name="company_status")
job_status_t = ENUM(*JOB_STATUS_VALUES, name="job_status")
application_status_t = ENUM(*APPLICATION_STATUS_VALUES, name="application_status")
qa_answer_type_t = ENUM(*QA_ANSWER_TYPE_VALUES, name="qa_answer_type")
outreach_type_t = ENUM(*OUTREACH_TYPE_VALUES, name="outreach_type")
scanner_kind_t = ENUM(*SCANNER_KIND_VALUES, name="scanner_kind")
ats_board_t = ENUM(*ATS_BOARD_VALUES, name="ats_board")
ats_org_status_t = ENUM(*ATS_ORG_STATUS_VALUES, name="ats_org_status")
pipeline_state_t = ENUM(*PIPELINE_STATE_VALUES, name="pipeline_state")


# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------
class Company(Base):
    """The user-facing CRM spine.

    Every LangGraph scanner ultimately promotes a raw ``raw_scrapes_*``
    row into this table (out of scope for v1 schema work). The Pydantic
    model :class:`backend.routes.companies.Company` mirrors these columns
    1-for-1. ``external_id`` is the dedupe key join with the ATS — for
    Ashby/Lever/Greenhouse it's the slug, for GitHub it's ``owner/repo``,
    for NGO listings it's the source URL.
    """

    __tablename__ = "companies"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    organization: Mapped[str] = mapped_column(Text, nullable=False)
    url: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Pydantic fields CompanyCard reads. The literal category is inlined
    # into a per-row CHECK constraint so a typo in application code can't
    # poison the enum until the next migration upgrades the type.
    category: Mapped[str] = mapped_column(
        company_category_t,
        nullable=False,
    )
    score: Mapped[float] = mapped_column(
        Float,
        CheckConstraint("score >= 0.0 AND score <= 1.0", name="companies_score_range"),
        nullable=False,
    )
    source: Mapped[str] = mapped_column(Text, nullable=False)
    tags: Mapped[list[str]] = mapped_column(
        ARRAY(Text),
        nullable=False,
        server_default="{}",
    )
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    published_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    location: Mapped[str | None] = mapped_column(Text, nullable=True)
    primary_language: Mapped[str | None] = mapped_column(Text, nullable=True)
    difficulty: Mapped[str | None] = mapped_column(Text, nullable=True)
    stars: Mapped[int | None] = mapped_column(Integer, nullable=True)
    company_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    hiring_signals: Mapped[list[str]] = mapped_column(
        ARRAY(Text),
        nullable=False,
        server_default="{}",
    )
    status: Mapped[str] = mapped_column(
        company_status_t,
        nullable=False,
        server_default="saved",
    )

    # Dedupe / external join key. Indexed so the boards runner can check
    # ``SELECT ... WHERE external_id = $1`` cheaply.
    external_id: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
        server_default=text("now()"),
    )

    __table_args__ = (
        # (category, status, published_at DESC) matches the React
        # CompanyFeed's "filter by category, sort by recency" path.
        Index(
            "idx_companies_feed",
            "category",
            "status",
            text("published_at DESC"),
        ),
        Index("idx_companies_external_id", "external_id"),
    )


# ---------------------------------------------------------------------------
# Per-scanner raw landing tables. Five separate tables satisfy the spec
# ("create a table for each to handle the opportunities individually") and
# let each scanner's loader not contend for locks on a single shared heap.
# Scrapes from the same external_id are deduped via the (external_id,
# scraped_at) partial index; downstream promotion to ``companies`` is
# out of scope for v1.
# ---------------------------------------------------------------------------
class RawScrapesFunding(Base):
    __tablename__ = "raw_scrapes_funding"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    external_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    source: Mapped[str] = mapped_column(Text, nullable=False)
    raw_payload: Mapped[dict] = mapped_column(JSONB, nullable=False)
    score: Mapped[float | None] = mapped_column(Float, nullable=True)
    company_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("companies.id", ondelete="SET NULL"),
        nullable=True,
    )
    scraped_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
    )
    promoted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    __table_args__ = (
        Index("idx_raw_funding_scraped_at", text("scraped_at DESC")),
        Index("idx_raw_funding_external", "external_id"),
    )


class RawScrapesRemote(Base):
    __tablename__ = "raw_scrapes_remote"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    external_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    source: Mapped[str] = mapped_column(Text, nullable=False)
    raw_payload: Mapped[dict] = mapped_column(JSONB, nullable=False)
    score: Mapped[float | None] = mapped_column(Float, nullable=True)
    company_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("companies.id", ondelete="SET NULL"),
        nullable=True,
    )
    scraped_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
    )
    promoted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    __table_args__ = (
        Index("idx_raw_remote_scraped_at", text("scraped_at DESC")),
    )


class RawScrapesNgos(Base):
    __tablename__ = "raw_scrapes_ngos"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    external_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    source: Mapped[str] = mapped_column(Text, nullable=False)
    raw_payload: Mapped[dict] = mapped_column(JSONB, nullable=False)
    score: Mapped[float | None] = mapped_column(Float, nullable=True)
    company_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("companies.id", ondelete="SET NULL"),
        nullable=True,
    )
    scraped_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
    )
    promoted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    __table_args__ = (
        Index("idx_raw_ngos_scraped_at", text("scraped_at DESC")),
    )


class RawScrapesOss(Base):
    __tablename__ = "raw_scrapes_oss"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    external_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    source: Mapped[str] = mapped_column(Text, nullable=False)
    raw_payload: Mapped[dict] = mapped_column(JSONB, nullable=False)
    score: Mapped[float | None] = mapped_column(Float, nullable=True)
    company_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("companies.id", ondelete="SET NULL"),
        nullable=True,
    )
    scraped_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
    )
    promoted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    __table_args__ = (
        Index("idx_raw_oss_scraped_at", text("scraped_at DESC")),
    )


class RawScrapesBoards(Base):
    __tablename__ = "raw_scrapes_boards"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    # ``external_id`` here is the (board, slug) tuple serialised as
    # ``"ashby:replicate"`` so a single index dedupe-scopes everything.
    external_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    source: Mapped[str] = mapped_column(Text, nullable=False)
    raw_payload: Mapped[dict] = mapped_column(JSONB, nullable=False)
    score: Mapped[float | None] = mapped_column(Float, nullable=True)
    company_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("companies.id", ondelete="SET NULL"),
        nullable=True,
    )
    scraped_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
    )
    promoted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    __table_args__ = (
        Index("idx_raw_boards_scraped_at", text("scraped_at DESC")),
        Index("idx_raw_boards_external", "external_id"),
    )


# ---------------------------------------------------------------------------
class ScannerRun(Base):
    """One row per scanner invocation — audit trail for reliability.

    Captures the wall-clock duration, item count, and per-run error
    summary so an on-call engineer can answer "what did the funding
    scanner see yesterday at 9 AM?" from SQL alone.
    """

    __tablename__ = "scanner_runs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    scanner: Mapped[str] = mapped_column(scanner_kind_t, nullable=False)
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    state: Mapped[str] = mapped_column(
        pipeline_state_t,
        nullable=False,
        server_default="running",
    )
    items_found: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    error_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    error_summary: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        Index("idx_scanner_runs_scanner_started", "scanner", text("started_at DESC")),
    )


# ---------------------------------------------------------------------------
class Job(Base):
    """The review-queue row source of truth for ``/api/jobs``.

    The Pydantic model :class:`backend.routes.jobs.Job` is 1-for-1 with
    these columns except for ``company_name`` — Postgres stores that as a
    derived copy on insert so the React ``JobsReview`` table can render
    without joining ``companies`` every page load.
    """

    __tablename__ = "jobs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    company_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("companies.id", ondelete="SET NULL"),
        nullable=True,
    )
    company_name: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(job_status_t, nullable=False)
    ats_type: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    url: Mapped[str] = mapped_column(Text, nullable=False)
    ai_fit_score: Mapped[float | None] = mapped_column(
        Float,
        CheckConstraint(
            "ai_fit_score IS NULL OR (ai_fit_score >= 0.0 AND ai_fit_score <= 1.0)",
            name="jobs_ai_fit_score_range",
        ),
        nullable=True,
    )
    ai_fit_reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)
    review_deadline: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # External (ATS) ID for dedupe against the runner's board fetch loop.
    external_id: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
        server_default=text("now()"),
    )

    __table_args__ = (
        # Partial index keeps the in-review queue lightning-fast even
        # when ``jobs`` balloons to tens of thousands of historical
        # approved/rejected rows.
        Index(
            "idx_jobs_in_review_deadline",
            text("review_deadline ASC"),
            postgresql_where=text("status = 'in_review'"),
        ),
        Index("idx_jobs_status_created", "status", text("created_at DESC")),
        Index("idx_jobs_external", "external_id"),
    )


# ---------------------------------------------------------------------------
class Application(Base):
    """Post-application lifecycle tracker. Matches
    :class:`backend.routes.applications.Application` 1-for-1."""

    __tablename__ = "applications"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    job_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("jobs.id", ondelete="SET NULL"),
        nullable=True,
    )
    job_title: Mapped[str] = mapped_column(Text, nullable=False)
    company_name: Mapped[str] = mapped_column(Text, nullable=False)
    submitted_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    status: Mapped[str] = mapped_column(application_status_t, nullable=False)
    last_email_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    submission_screenshot_path: Mapped[str | None] = mapped_column(Text, nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
        server_default=text("now()"),
    )

    __table_args__ = (
        Index("idx_applications_status_submitted", "status", text("submitted_at DESC")),
    )


# ---------------------------------------------------------------------------
class QABankEntry(Base):
    """Q&A bank — server-side answers used to auto-fill application forms."""

    __tablename__ = "qa_bank_entries"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    question_pattern: Mapped[str] = mapped_column(
        Text, nullable=False, unique=True
    )
    canonical_question: Mapped[str] = mapped_column(Text, nullable=False)
    answer: Mapped[str | None] = mapped_column(Text, nullable=True)
    answer_type: Mapped[str] = mapped_column(qa_answer_type_t, nullable=False)
    times_used: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
        server_default=text("now()"),
    )

    __table_args__ = (
        # Sort by ``times_used DESC`` is the React QABank default; an
        # index keeps it cheap as the bank grows.
        Index("idx_qa_bank_times_used", text("times_used DESC")),
    )


# ---------------------------------------------------------------------------
class Resume(Base):
    """Resume metadata — bytes live in Supabase Storage, NOT in Postgres.

    Schema rationale: storing 10 MiB blobs in Postgres ``bytea`` blows
    the buffer cache, degrades the WAL stream, and bloats pg_dump
    backups by gigabytes. Supabase Storage is a regular S3-compatible
    bucket and the integration is a one-liner on the route that handles
    ``POST /api/resumes`` (out of scope for v1 schema work).
    """

    __tablename__ = "resumes"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    size_bytes: Mapped[int] = mapped_column(Integer, nullable=False)
    uploaded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    tags: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, server_default="{}"
    )
    is_default: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    storage_path: Mapped[str] = mapped_column(Text, nullable=False)

    __table_args__ = (
        # Single-default invariant: at most one row may have
        # ``is_default = true``. The Postgres partial unique index
        # enforces this in the engine — ``patch_resume`` no longer
        # has to demote siblings in application logic.
        Index(
            "uq_resumes_single_default",
            "is_default",
            unique=True,
            postgresql_where=text("is_default = true"),
        ),
    )


# ---------------------------------------------------------------------------
class OutreachMessage(Base):
    """Generated outreach messages keyed by company.

    Mirrors :class:`backend.routes.outreach.OutreachMessage` 1-for-1.
    The ``q1``/``q2`` foreign keys make the resume/QA selection
    traceable from a single SQL query — useful when a recruiter says
    "which profile did you send to Vercel last week?".
    """

    __tablename__ = "outreach_messages"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    company_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("companies.id", ondelete="SET NULL"),
        nullable=True,
    )
    type: Mapped[str] = mapped_column(outreach_type_t, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    resume_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    resume_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    qa_snippet_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    qa_snippet: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        # (company_id, created_at DESC) is the React OutreachPanel's
        # "messages for company X, newest first" read path.
        Index(
            "idx_outreach_company_created",
            "company_id",
            text("created_at DESC"),
        ),
    )


# ---------------------------------------------------------------------------
class Preferences(Base):
    """Singleton user preferences.

    The ``CHECK (id = 1)`` constraint enforces one-row semantics at the
    engine level — cheaper and more reliable than application-level
    guards, and it makes ``SELECT * FROM preferences`` a guaranteed
    fetch without pagination logic.
    """

    __tablename__ = "preferences"

    id: Mapped[int] = mapped_column(
        Integer,
        CheckConstraint("id = 1", name="preferences_singleton"),
        primary_key=True,
        server_default="1",
    )
    target_roles: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, server_default="{}"
    )
    review_window_hours: Mapped[float] = mapped_column(
        Float,
        CheckConstraint(
            "review_window_hours >= 0.5 AND review_window_hours <= 48.0",
            name="preferences_window_range",
        ),
        nullable=False,
        server_default="2.0",
    )
    job_fit_threshold: Mapped[float] = mapped_column(
        Float,
        CheckConstraint(
            "job_fit_threshold >= 0.0 AND job_fit_threshold <= 1.0",
            name="preferences_threshold_range",
        ),
        nullable=False,
        server_default="0.6",
    )
    send_followup_emails: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )
    # Optional seniority band — drives the
    # :func:`utils.filters.is_relevant_role` filter when populated.
    # ``Text`` rather than ENUM so adding a new tier in
    # :data:`utils.filters.SENIORITY_TIERS` doesn't require a Postgres
    # ``ALTER TYPE`` migration; Pydantic validates the wire form so
    # only known values reach the DB via the route handler.
    min_seniority: Mapped[str | None] = mapped_column(Text, nullable=True)
    max_seniority: Mapped[str | None] = mapped_column(Text, nullable=True)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
        server_default=text("now()"),
    )


# ---------------------------------------------------------------------------
class PipelineStatus(Base):
    """Singleton holding the current LangGraph run state.

    Mirrors the in-memory ``_PIPELINE_STATE`` dict in
    :mod:`backend.routes.pipeline`. ``last_run_counts`` is JSONB so a
    future schema change to per-domain counts doesn't require a DB
    migration — just a JSONB path update on the read side.
    """

    __tablename__ = "pipeline_status"

    id: Mapped[int] = mapped_column(
        Integer,
        CheckConstraint("id = 1", name="pipeline_status_singleton"),
        primary_key=True,
        server_default="1",
    )
    state: Mapped[str] = mapped_column(
        pipeline_state_t, nullable=False, server_default="idle"
    )
    last_run_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    last_run_duration_seconds: Mapped[float | None] = mapped_column(
        Float, nullable=True
    )
    last_run_counts: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    recent_error: Mapped[str | None] = mapped_column(Text, nullable=True)
    interval_hours: Mapped[int] = mapped_column(
        Integer,
        CheckConstraint(
            "interval_hours IN (1, 2, 4, 6, 12, 24)",
            name="pipeline_status_interval_allowed",
        ),
        nullable=False,
        server_default="1",
    )
    schedule_updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )


# ---------------------------------------------------------------------------
class BoardSeenJob(Base):
    """Replaces the on-disk ``backend/data/seen.json`` file.

    The hourly boards runner currently consults a single-process JSON
    file for "have I delivered this job slug before?". That works for
    one Docker worker, but two concurrent apply-workers would race on
    the read-modify-write cycle. A Postgres table with
    ``INSERT ... ON CONFLICT DO NOTHING`` makes dedup atomic without
    any concurrency gymnastics.
    """

    __tablename__ = "board_seen_jobs"

    # The PK is the dedupe key — typically ``"<board>:<job-id>"``. Text
    # rather than UUID because the boards (Ashby/Lever/Greenhouse)
    # assign their own opaque string IDs and re-encoding them wastes
    # 16 bytes per row.
    job_id_hash: Mapped[str] = mapped_column(Text, primary_key=True)
    board: Mapped[str] = mapped_column(ats_board_t, nullable=False)
    company_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("companies.id", ondelete="SET NULL"),
        nullable=True,
    )
    first_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
    )
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
    )
    times_seen: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="1"
    )

    __table_args__ = (
        Index("idx_board_seen_board_last_seen", "board", text("last_seen_at DESC")),
    )


# ---------------------------------------------------------------------------
class AtsDiscoveredOrg(Base):
    """Replaces the per-board JSON files ``backend/data/<board>_missing_orgs.json``.

    Tracks the consecutive-failure count for each (board, slug) so the
    :func:`MISSING_THRESHOLD = 3` benching logic in
    :mod:`backend.pipeline.nodes.jobs_boards.runner` can be expressed
    in a single ``WHERE status = 'active'`` query.
    """

    __tablename__ = "ats_discovered_orgs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    board: Mapped[str] = mapped_column(ats_board_t, nullable=False)
    slug: Mapped[str] = mapped_column(Text, nullable=False)
    company_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("companies.id", ondelete="SET NULL"),
        nullable=True,
    )
    status: Mapped[str] = mapped_column(
        ats_org_status_t, nullable=False, server_default="active"
    )
    consecutive_failures: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    last_checked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    first_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=text("now()"),
    )

    __table_args__ = (
        # (board, slug) is the dedupe key — same org never appears twice
        # on a board. The boards runner does INSERT ON CONFLICT here.
        UniqueConstraint("board", "slug", name="uq_ats_orgs_board_slug"),
        Index("idx_ats_orgs_status", "status", "consecutive_failures"),
    )


# ---------------------------------------------------------------------------
# Re-export of the COMPLETE metadata so env.py / Alembic can pull a single
# symbol without chasing imports.
__all__ = [
    "Base",
    "Company",
    "RawScrapesFunding",
    "RawScrapesRemote",
    "RawScrapesNgos",
    "RawScrapesOss",
    "RawScrapesBoards",
    "ScannerRun",
    "Job",
    "Application",
    "QABankEntry",
    "Resume",
    "OutreachMessage",
    "Preferences",
    "PipelineStatus",
    "BoardSeenJob",
    "AtsDiscoveredOrg",
]
