"""Tests for the /settings (preferences) endpoint schema + singleton seed."""
from types import SimpleNamespace

import pytest
from pydantic import ValidationError

from app.api.settings import get_or_seed_preferences
from app.models.preferences import (
    DEFAULT_JOB_FIT_THRESHOLD,
    DEFAULT_REVIEW_WINDOW_HOURS,
    DEFAULT_SEND_FOLLOWUP_EMAILS,
    DEFAULT_TARGET_ROLES,
    Preferences,
)
from app.schemas.preferences import PreferencesResponse, PreferencesUpdate


# --- PreferencesUpdate schema -------------------------------------------------


def test_update_rejects_review_window_below_min() -> None:
    with pytest.raises(ValidationError):
        PreferencesUpdate(review_window_hours=0.1)


def test_update_rejects_review_window_above_max() -> None:
    with pytest.raises(ValidationError):
        PreferencesUpdate(review_window_hours=49)


def test_update_rejects_fit_below_zero() -> None:
    with pytest.raises(ValidationError):
        PreferencesUpdate(job_fit_threshold=-0.01)


def test_update_rejects_fit_above_one() -> None:
    with pytest.raises(ValidationError):
        PreferencesUpdate(job_fit_threshold=1.5)


def test_update_accepts_boundaries() -> None:
    PreferencesUpdate(review_window_hours=0.5, job_fit_threshold=0.0)
    PreferencesUpdate(review_window_hours=48, job_fit_threshold=1.0)


def test_update_exclude_unset_keeps_omitted_fields() -> None:
    """`exclude_unset=True` is the load-bearing PATCH idiom: unmentioned
    keys must not collapse to Pydantic defaults."""
    payload = PreferencesUpdate(review_window_hours=3.0)
    dump = payload.model_dump(exclude_unset=True)
    assert dump == {"review_window_hours": 3.0}


def test_update_exclude_unset_with_multiple_fields() -> None:
    payload = PreferencesUpdate(
        review_window_hours=3.0,
        send_followup_emails=False,
    )
    dump = payload.model_dump(exclude_unset=True)
    assert dump == {"review_window_hours": 3.0, "send_followup_emails": False}


# --- Response schema ---------------------------------------------------------


def test_response_round_trips() -> None:
    response = PreferencesResponse(
        target_roles=["AI Engineer", "Backend"],
        review_window_hours=DEFAULT_REVIEW_WINDOW_HOURS,
        job_fit_threshold=DEFAULT_JOB_FIT_THRESHOLD,
        send_followup_emails=DEFAULT_SEND_FOLLOWUP_EMAILS,
        updated_at="2026-01-01T00:00:00Z",
    )
    dumped = response.model_dump()
    assert dumped["target_roles"] == ["AI Engineer", "Backend"]
    assert dumped["review_window_hours"] == DEFAULT_REVIEW_WINDOW_HOURS


# --- Defaults exported stay aligned with backend ----------------------------


def test_default_target_roles_non_empty() -> None:
    assert len(DEFAULT_TARGET_ROLES) >= 1
    assert all(isinstance(r, str) and r for r in DEFAULT_TARGET_ROLES)


# --- Singleton seed (no real DB — fake AsyncSession) -------------------------


@pytest.mark.asyncio
async def test_seed_inserts_default_when_missing() -> None:
    inserted: dict = {}

    class _FakeSession:
        async def get(self, _model, _id):
            return None

        def add(self, obj):
            inserted["obj"] = obj

        async def commit(self):
            inserted["committed"] = True

        async def refresh(self, obj):
            inserted["refreshed"] = True

    sess = _FakeSession()
    result = await get_or_seed_preferences(sess)

    assert inserted.get("committed") is True
    assert inserted.get("refreshed") is True
    assert isinstance(inserted["obj"], Preferences)
    assert result.target_roles == list(DEFAULT_TARGET_ROLES)
    assert result.review_window_hours == DEFAULT_REVIEW_WINDOW_HOURS
    assert result.send_followup_emails is True


@pytest.mark.asyncio
async def test_seed_returns_existing_row_without_writing() -> None:
    fake = SimpleNamespace(
        target_roles=["x"],
        review_window_hours=4.0,
        job_fit_threshold=0.5,
        send_followup_emails=False,
        updated_at="2026-01-01T00:00:00Z",
    )
    seen: dict = {"committed": 0, "added": 0}

    class _FakeSession:
        async def get(self, _model, _id):
            return fake

        def add(self, obj):
            seen["added"] += 1

        async def commit(self):
            seen["committed"] += 1

        async def refresh(self, obj):
            pass

    result = await get_or_seed_preferences(_FakeSession())
    assert result is fake
    assert seen["committed"] == 0
    assert seen["added"] == 0


# --- Route registration via OpenAPI introspection ----------------------------


def test_settings_routes_registered() -> None:
    from app.main import app

    # Use OpenAPI schema (generated by FastAPI from registered routes) instead
    # of walking app.routes directly — Mount objects and Route wrappers don't
    # all expose a `.path` attribute consistently.
    paths = list(app.openapi().get("paths", {}).keys())
    assert "/api/settings" in paths, paths
    # Both verbs should be declared on the new endpoint.
    assert "get" in app.openapi()["paths"]["/api/settings"]
    assert "patch" in app.openapi()["paths"]["/api/settings"]
